plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

npmRegistryServer: "https://registry.yarnpkg.com"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmAlwaysAuth: false

nodeLinker: node-modules

nmSelfReferences: false